### ISSUE TITLE
Error loading images when running run_examples.sh

### ISSUE THREAD

**Issue by xxl007** [henzler/neuralmaterial#3]
Traceback (most recent call last):
  File "scripts/test.py", line 58, in <module>
    image = tfm(io.read_image(image_dirs[0]))[None]
  File "/home/galem/anaconda3/envs/neuralmaterial/lib/python3.8/site-packages/torchvision/io/image.py", line 230, in read_image
    return decode_image(data)
  File "/home/galem/anaconda3/envs/neuralmaterial/lib/python3.8/site-packages/torchvision/io/image.py", line 211, in decode_image
    output = torch.ops.image.decode_image(input)
RuntimeError: Unsupported image file. Only jpeg and png are currently supported.

**Comment by Theo-Wu** [comment]
Can you ensure all the images in the test file are downloaded perfectly? Are they all able to open and show? 
If their sizes are only 1kb, then there are not downloaded successfully.
